//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Alumno_Actividad", "Actividad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.Actividad), "Alumno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Alumno), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Ingreso_Actividad", "Actividad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.Actividad), "Ingreso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Ingreso), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Alumno_Grupo", "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.Grupo), "Alumno", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Alumno), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Ingreso_Alumno", "Alumno", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Akros.Models.Alumno), "Ingreso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Ingreso), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Egreso_Concepto", "Concepto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.Concepto), "Egreso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Egreso), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Ingreso_FormaPago", "FormaPago", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.FormaPago), "Ingreso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Ingreso), true)]
[assembly: EdmRelationshipAttribute("AkrosModel", "FK_Grupo_Actividad", "Actividad", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Akros.Models.Actividad), "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Akros.Models.Grupo), true)]

#endregion

namespace Akros.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class AkrosEntities6 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto AkrosEntities6 usando la cadena de conexión encontrada en la sección 'AkrosEntities6' del archivo de configuración de la aplicación.
        /// </summary>
        public AkrosEntities6() : base("name=AkrosEntities6", "AkrosEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AkrosEntities6.
        /// </summary>
        public AkrosEntities6(string connectionString) : base(connectionString, "AkrosEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto AkrosEntities6.
        /// </summary>
        public AkrosEntities6(EntityConnection connection) : base(connection, "AkrosEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Actividad> Actividad
        {
            get
            {
                if ((_Actividad == null))
                {
                    _Actividad = base.CreateObjectSet<Actividad>("Actividad");
                }
                return _Actividad;
            }
        }
        private ObjectSet<Actividad> _Actividad;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alumno> Alumno
        {
            get
            {
                if ((_Alumno == null))
                {
                    _Alumno = base.CreateObjectSet<Alumno>("Alumno");
                }
                return _Alumno;
            }
        }
        private ObjectSet<Alumno> _Alumno;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Concepto> Concepto
        {
            get
            {
                if ((_Concepto == null))
                {
                    _Concepto = base.CreateObjectSet<Concepto>("Concepto");
                }
                return _Concepto;
            }
        }
        private ObjectSet<Concepto> _Concepto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Egreso> Egreso
        {
            get
            {
                if ((_Egreso == null))
                {
                    _Egreso = base.CreateObjectSet<Egreso>("Egreso");
                }
                return _Egreso;
            }
        }
        private ObjectSet<Egreso> _Egreso;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<FormaPago> FormaPago
        {
            get
            {
                if ((_FormaPago == null))
                {
                    _FormaPago = base.CreateObjectSet<FormaPago>("FormaPago");
                }
                return _FormaPago;
            }
        }
        private ObjectSet<FormaPago> _FormaPago;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Grupo> Grupo
        {
            get
            {
                if ((_Grupo == null))
                {
                    _Grupo = base.CreateObjectSet<Grupo>("Grupo");
                }
                return _Grupo;
            }
        }
        private ObjectSet<Grupo> _Grupo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Ingreso> Ingreso
        {
            get
            {
                if ((_Ingreso == null))
                {
                    _Ingreso = base.CreateObjectSet<Ingreso>("Ingreso");
                }
                return _Ingreso;
            }
        }
        private ObjectSet<Ingreso> _Ingreso;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Actividad. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToActividad(Actividad actividad)
        {
            base.AddObject("Actividad", actividad);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumno. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumno(Alumno alumno)
        {
            base.AddObject("Alumno", alumno);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Concepto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToConcepto(Concepto concepto)
        {
            base.AddObject("Concepto", concepto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Egreso. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEgreso(Egreso egreso)
        {
            base.AddObject("Egreso", egreso);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet FormaPago. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToFormaPago(FormaPago formaPago)
        {
            base.AddObject("FormaPago", formaPago);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Grupo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToGrupo(Grupo grupo)
        {
            base.AddObject("Grupo", grupo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Ingreso. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToIngreso(Ingreso ingreso)
        {
            base.AddObject("Ingreso", ingreso);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Actividad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Actividad : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Actividad.
        /// </summary>
        /// <param name="id_Actividad">Valor inicial de la propiedad Id_Actividad.</param>
        /// <param name="detalle">Valor inicial de la propiedad Detalle.</param>
        public static Actividad CreateActividad(global::System.Int32 id_Actividad, global::System.String detalle)
        {
            Actividad actividad = new Actividad();
            actividad.Id_Actividad = id_Actividad;
            actividad.Detalle = detalle;
            return actividad;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Actividad
        {
            get
            {
                return _Id_Actividad;
            }
            set
            {
                if (_Id_Actividad != value)
                {
                    OnId_ActividadChanging(value);
                    ReportPropertyChanging("Id_Actividad");
                    _Id_Actividad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Actividad");
                    OnId_ActividadChanged();
                }
            }
        }
        private global::System.Int32 _Id_Actividad;
        partial void OnId_ActividadChanging(global::System.Int32 value);
        partial void OnId_ActividadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Detalle
        {
            get
            {
                return _Detalle;
            }
            set
            {
                OnDetalleChanging(value);
                ReportPropertyChanging("Detalle");
                _Detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Detalle");
                OnDetalleChanged();
            }
        }
        private global::System.String _Detalle;
        partial void OnDetalleChanging(global::System.String value);
        partial void OnDetalleChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Alumno_Actividad", "Alumno")]
        public EntityCollection<Alumno> Alumno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Alumno>("AkrosModel.FK_Alumno_Actividad", "Alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Alumno>("AkrosModel.FK_Alumno_Actividad", "Alumno", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_Actividad", "Ingreso")]
        public EntityCollection<Ingreso> Ingreso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_Actividad", "Ingreso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_Actividad", "Ingreso", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Grupo_Actividad", "Grupo")]
        public EntityCollection<Grupo> Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grupo>("AkrosModel.FK_Grupo_Actividad", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grupo>("AkrosModel.FK_Grupo_Actividad", "Grupo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumno : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alumno.
        /// </summary>
        /// <param name="dNI">Valor inicial de la propiedad DNI.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad Apellido.</param>
        /// <param name="id_Actividad">Valor inicial de la propiedad Id_Actividad.</param>
        /// <param name="id_Grupo">Valor inicial de la propiedad Id_Grupo.</param>
        /// <param name="cuota">Valor inicial de la propiedad Cuota.</param>
        /// <param name="nacimiento">Valor inicial de la propiedad Nacimiento.</param>
        /// <param name="antecedentes">Valor inicial de la propiedad Antecedentes.</param>
        /// <param name="certificado">Valor inicial de la propiedad Certificado.</param>
        public static Alumno CreateAlumno(global::System.Int32 dNI, global::System.String nombre, global::System.String apellido, global::System.Int32 id_Actividad, global::System.Int32 id_Grupo, global::System.Int32 cuota, global::System.DateTime nacimiento, global::System.Boolean antecedentes, global::System.Boolean certificado)
        {
            Alumno alumno = new Alumno();
            alumno.DNI = dNI;
            alumno.Nombre = nombre;
            alumno.Apellido = apellido;
            alumno.Id_Actividad = id_Actividad;
            alumno.Id_Grupo = id_Grupo;
            alumno.Cuota = cuota;
            alumno.Nacimiento = nacimiento;
            alumno.Antecedentes = antecedentes;
            alumno.Certificado = certificado;
            return alumno;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                if (_DNI != value)
                {
                    OnDNIChanging(value);
                    ReportPropertyChanging("DNI");
                    _DNI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DNI");
                    OnDNIChanged();
                }
            }
        }
        private global::System.Int32 _DNI;
        partial void OnDNIChanging(global::System.Int32 value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Actividad
        {
            get
            {
                return _Id_Actividad;
            }
            set
            {
                OnId_ActividadChanging(value);
                ReportPropertyChanging("Id_Actividad");
                _Id_Actividad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Actividad");
                OnId_ActividadChanged();
            }
        }
        private global::System.Int32 _Id_Actividad;
        partial void OnId_ActividadChanging(global::System.Int32 value);
        partial void OnId_ActividadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Grupo
        {
            get
            {
                return _Id_Grupo;
            }
            set
            {
                OnId_GrupoChanging(value);
                ReportPropertyChanging("Id_Grupo");
                _Id_Grupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Grupo");
                OnId_GrupoChanged();
            }
        }
        private global::System.Int32 _Id_Grupo;
        partial void OnId_GrupoChanging(global::System.Int32 value);
        partial void OnId_GrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cuota
        {
            get
            {
                return _Cuota;
            }
            set
            {
                OnCuotaChanging(value);
                ReportPropertyChanging("Cuota");
                _Cuota = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cuota");
                OnCuotaChanged();
            }
        }
        private global::System.Int32 _Cuota;
        partial void OnCuotaChanging(global::System.Int32 value);
        partial void OnCuotaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Nacimiento
        {
            get
            {
                return _Nacimiento;
            }
            set
            {
                OnNacimientoChanging(value);
                ReportPropertyChanging("Nacimiento");
                _Nacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nacimiento");
                OnNacimientoChanged();
            }
        }
        private global::System.DateTime _Nacimiento;
        partial void OnNacimientoChanging(global::System.DateTime value);
        partial void OnNacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Domicilio
        {
            get
            {
                return _Domicilio;
            }
            set
            {
                OnDomicilioChanging(value);
                ReportPropertyChanging("Domicilio");
                _Domicilio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Domicilio");
                OnDomicilioChanged();
            }
        }
        private global::System.String _Domicilio;
        partial void OnDomicilioChanging(global::System.String value);
        partial void OnDomicilioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private Nullable<global::System.Int32> _Tel;
        partial void OnTelChanging(Nullable<global::System.Int32> value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TelEmergencia
        {
            get
            {
                return _TelEmergencia;
            }
            set
            {
                OnTelEmergenciaChanging(value);
                ReportPropertyChanging("TelEmergencia");
                _TelEmergencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TelEmergencia");
                OnTelEmergenciaChanged();
            }
        }
        private Nullable<global::System.Int32> _TelEmergencia;
        partial void OnTelEmergenciaChanging(Nullable<global::System.Int32> value);
        partial void OnTelEmergenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cel
        {
            get
            {
                return _Cel;
            }
            set
            {
                OnCelChanging(value);
                ReportPropertyChanging("Cel");
                _Cel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cel");
                OnCelChanged();
            }
        }
        private Nullable<global::System.Int32> _Cel;
        partial void OnCelChanging(Nullable<global::System.Int32> value);
        partial void OnCelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObraSocial
        {
            get
            {
                return _ObraSocial;
            }
            set
            {
                OnObraSocialChanging(value);
                ReportPropertyChanging("ObraSocial");
                _ObraSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObraSocial");
                OnObraSocialChanged();
            }
        }
        private global::System.String _ObraSocial;
        partial void OnObraSocialChanging(global::System.String value);
        partial void OnObraSocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Antecedentes
        {
            get
            {
                return _Antecedentes;
            }
            set
            {
                OnAntecedentesChanging(value);
                ReportPropertyChanging("Antecedentes");
                _Antecedentes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Antecedentes");
                OnAntecedentesChanged();
            }
        }
        private global::System.Boolean _Antecedentes;
        partial void OnAntecedentesChanging(global::System.Boolean value);
        partial void OnAntecedentesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AntOpcional
        {
            get
            {
                return _AntOpcional;
            }
            set
            {
                OnAntOpcionalChanging(value);
                ReportPropertyChanging("AntOpcional");
                _AntOpcional = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AntOpcional");
                OnAntOpcionalChanged();
            }
        }
        private global::System.String _AntOpcional;
        partial void OnAntOpcionalChanging(global::System.String value);
        partial void OnAntOpcionalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Certificado
        {
            get
            {
                return _Certificado;
            }
            set
            {
                OnCertificadoChanging(value);
                ReportPropertyChanging("Certificado");
                _Certificado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Certificado");
                OnCertificadoChanged();
            }
        }
        private global::System.Boolean _Certificado;
        partial void OnCertificadoChanging(global::System.Boolean value);
        partial void OnCertificadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Alumno_Actividad", "Actividad")]
        public Actividad Actividad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Alumno_Actividad", "Actividad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Alumno_Actividad", "Actividad").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actividad> ActividadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Alumno_Actividad", "Actividad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actividad>("AkrosModel.FK_Alumno_Actividad", "Actividad", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Alumno_Grupo", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("AkrosModel.FK_Alumno_Grupo", "Grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("AkrosModel.FK_Alumno_Grupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("AkrosModel.FK_Alumno_Grupo", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("AkrosModel.FK_Alumno_Grupo", "Grupo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_Alumno", "Ingreso")]
        public EntityCollection<Ingreso> Ingreso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_Alumno", "Ingreso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_Alumno", "Ingreso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Concepto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Concepto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Concepto.
        /// </summary>
        /// <param name="id_Concepto">Valor inicial de la propiedad Id_Concepto.</param>
        /// <param name="detalle">Valor inicial de la propiedad Detalle.</param>
        public static Concepto CreateConcepto(global::System.Int32 id_Concepto, global::System.String detalle)
        {
            Concepto concepto = new Concepto();
            concepto.Id_Concepto = id_Concepto;
            concepto.Detalle = detalle;
            return concepto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Concepto
        {
            get
            {
                return _Id_Concepto;
            }
            set
            {
                if (_Id_Concepto != value)
                {
                    OnId_ConceptoChanging(value);
                    ReportPropertyChanging("Id_Concepto");
                    _Id_Concepto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Concepto");
                    OnId_ConceptoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Concepto;
        partial void OnId_ConceptoChanging(global::System.Int32 value);
        partial void OnId_ConceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Detalle
        {
            get
            {
                return _Detalle;
            }
            set
            {
                OnDetalleChanging(value);
                ReportPropertyChanging("Detalle");
                _Detalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Detalle");
                OnDetalleChanged();
            }
        }
        private global::System.String _Detalle;
        partial void OnDetalleChanging(global::System.String value);
        partial void OnDetalleChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Egreso_Concepto", "Egreso")]
        public EntityCollection<Egreso> Egreso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Egreso>("AkrosModel.FK_Egreso_Concepto", "Egreso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Egreso>("AkrosModel.FK_Egreso_Concepto", "Egreso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Egreso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Egreso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Egreso.
        /// </summary>
        /// <param name="id_Egreso">Valor inicial de la propiedad Id_Egreso.</param>
        /// <param name="id_Concepto">Valor inicial de la propiedad Id_Concepto.</param>
        /// <param name="mes">Valor inicial de la propiedad Mes.</param>
        /// <param name="fecha_Egreso">Valor inicial de la propiedad Fecha_Egreso.</param>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        public static Egreso CreateEgreso(global::System.Int32 id_Egreso, global::System.Int32 id_Concepto, global::System.String mes, global::System.DateTime fecha_Egreso, global::System.Int32 cantidad)
        {
            Egreso egreso = new Egreso();
            egreso.Id_Egreso = id_Egreso;
            egreso.Id_Concepto = id_Concepto;
            egreso.Mes = mes;
            egreso.Fecha_Egreso = fecha_Egreso;
            egreso.Cantidad = cantidad;
            return egreso;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Egreso
        {
            get
            {
                return _Id_Egreso;
            }
            set
            {
                if (_Id_Egreso != value)
                {
                    OnId_EgresoChanging(value);
                    ReportPropertyChanging("Id_Egreso");
                    _Id_Egreso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Egreso");
                    OnId_EgresoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Egreso;
        partial void OnId_EgresoChanging(global::System.Int32 value);
        partial void OnId_EgresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Concepto
        {
            get
            {
                return _Id_Concepto;
            }
            set
            {
                OnId_ConceptoChanging(value);
                ReportPropertyChanging("Id_Concepto");
                _Id_Concepto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Concepto");
                OnId_ConceptoChanged();
            }
        }
        private global::System.Int32 _Id_Concepto;
        partial void OnId_ConceptoChanging(global::System.Int32 value);
        partial void OnId_ConceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mes
        {
            get
            {
                return _Mes;
            }
            set
            {
                OnMesChanging(value);
                ReportPropertyChanging("Mes");
                _Mes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Mes");
                OnMesChanged();
            }
        }
        private global::System.String _Mes;
        partial void OnMesChanging(global::System.String value);
        partial void OnMesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha_Egreso
        {
            get
            {
                return _Fecha_Egreso;
            }
            set
            {
                OnFecha_EgresoChanging(value);
                ReportPropertyChanging("Fecha_Egreso");
                _Fecha_Egreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Egreso");
                OnFecha_EgresoChanged();
            }
        }
        private global::System.DateTime _Fecha_Egreso;
        partial void OnFecha_EgresoChanging(global::System.DateTime value);
        partial void OnFecha_EgresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Egreso_Concepto", "Concepto")]
        public Concepto Concepto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("AkrosModel.FK_Egreso_Concepto", "Concepto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("AkrosModel.FK_Egreso_Concepto", "Concepto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Concepto> ConceptoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Concepto>("AkrosModel.FK_Egreso_Concepto", "Concepto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Concepto>("AkrosModel.FK_Egreso_Concepto", "Concepto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="FormaPago")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormaPago : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto FormaPago.
        /// </summary>
        /// <param name="id_Pago">Valor inicial de la propiedad Id_Pago.</param>
        /// <param name="detalles">Valor inicial de la propiedad Detalles.</param>
        public static FormaPago CreateFormaPago(global::System.Int32 id_Pago, global::System.String detalles)
        {
            FormaPago formaPago = new FormaPago();
            formaPago.Id_Pago = id_Pago;
            formaPago.Detalles = detalles;
            return formaPago;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Pago
        {
            get
            {
                return _Id_Pago;
            }
            set
            {
                if (_Id_Pago != value)
                {
                    OnId_PagoChanging(value);
                    ReportPropertyChanging("Id_Pago");
                    _Id_Pago = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Pago");
                    OnId_PagoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Pago;
        partial void OnId_PagoChanging(global::System.Int32 value);
        partial void OnId_PagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Detalles
        {
            get
            {
                return _Detalles;
            }
            set
            {
                OnDetallesChanging(value);
                ReportPropertyChanging("Detalles");
                _Detalles = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Detalles");
                OnDetallesChanged();
            }
        }
        private global::System.String _Detalles;
        partial void OnDetallesChanging(global::System.String value);
        partial void OnDetallesChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_FormaPago", "Ingreso")]
        public EntityCollection<Ingreso> Ingreso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_FormaPago", "Ingreso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingreso>("AkrosModel.FK_Ingreso_FormaPago", "Ingreso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Grupo.
        /// </summary>
        /// <param name="id_Grupo">Valor inicial de la propiedad Id_Grupo.</param>
        /// <param name="dias">Valor inicial de la propiedad Dias.</param>
        /// <param name="horario">Valor inicial de la propiedad Horario.</param>
        /// <param name="id_Actividad">Valor inicial de la propiedad Id_Actividad.</param>
        public static Grupo CreateGrupo(global::System.Int32 id_Grupo, global::System.String dias, global::System.String horario, global::System.Int32 id_Actividad)
        {
            Grupo grupo = new Grupo();
            grupo.Id_Grupo = id_Grupo;
            grupo.Dias = dias;
            grupo.Horario = horario;
            grupo.Id_Actividad = id_Actividad;
            return grupo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Grupo
        {
            get
            {
                return _Id_Grupo;
            }
            set
            {
                if (_Id_Grupo != value)
                {
                    OnId_GrupoChanging(value);
                    ReportPropertyChanging("Id_Grupo");
                    _Id_Grupo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Grupo");
                    OnId_GrupoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Grupo;
        partial void OnId_GrupoChanging(global::System.Int32 value);
        partial void OnId_GrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Dias
        {
            get
            {
                return _Dias;
            }
            set
            {
                OnDiasChanging(value);
                ReportPropertyChanging("Dias");
                _Dias = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Dias");
                OnDiasChanged();
            }
        }
        private global::System.String _Dias;
        partial void OnDiasChanging(global::System.String value);
        partial void OnDiasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Horario
        {
            get
            {
                return _Horario;
            }
            set
            {
                OnHorarioChanging(value);
                ReportPropertyChanging("Horario");
                _Horario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Horario");
                OnHorarioChanged();
            }
        }
        private global::System.String _Horario;
        partial void OnHorarioChanging(global::System.String value);
        partial void OnHorarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Actividad
        {
            get
            {
                return _Id_Actividad;
            }
            set
            {
                OnId_ActividadChanging(value);
                ReportPropertyChanging("Id_Actividad");
                _Id_Actividad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Actividad");
                OnId_ActividadChanged();
            }
        }
        private global::System.Int32 _Id_Actividad;
        partial void OnId_ActividadChanging(global::System.Int32 value);
        partial void OnId_ActividadChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Alumno_Grupo", "Alumno")]
        public EntityCollection<Alumno> Alumno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Alumno>("AkrosModel.FK_Alumno_Grupo", "Alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Alumno>("AkrosModel.FK_Alumno_Grupo", "Alumno", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Grupo_Actividad", "Actividad")]
        public Actividad Actividad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Grupo_Actividad", "Actividad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Grupo_Actividad", "Actividad").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actividad> ActividadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Grupo_Actividad", "Actividad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actividad>("AkrosModel.FK_Grupo_Actividad", "Actividad", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AkrosModel", Name="Ingreso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingreso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Ingreso.
        /// </summary>
        /// <param name="id_Ingreso">Valor inicial de la propiedad Id_Ingreso.</param>
        /// <param name="id_Actividad">Valor inicial de la propiedad Id_Actividad.</param>
        /// <param name="fecha_ingreso">Valor inicial de la propiedad Fecha_ingreso.</param>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        /// <param name="id_Pago">Valor inicial de la propiedad Id_Pago.</param>
        public static Ingreso CreateIngreso(global::System.Int32 id_Ingreso, global::System.Int32 id_Actividad, global::System.DateTime fecha_ingreso, global::System.Int32 cantidad, global::System.Int32 id_Pago)
        {
            Ingreso ingreso = new Ingreso();
            ingreso.Id_Ingreso = id_Ingreso;
            ingreso.Id_Actividad = id_Actividad;
            ingreso.Fecha_ingreso = fecha_ingreso;
            ingreso.Cantidad = cantidad;
            ingreso.Id_Pago = id_Pago;
            return ingreso;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Ingreso
        {
            get
            {
                return _Id_Ingreso;
            }
            set
            {
                if (_Id_Ingreso != value)
                {
                    OnId_IngresoChanging(value);
                    ReportPropertyChanging("Id_Ingreso");
                    _Id_Ingreso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_Ingreso");
                    OnId_IngresoChanged();
                }
            }
        }
        private global::System.Int32 _Id_Ingreso;
        partial void OnId_IngresoChanging(global::System.Int32 value);
        partial void OnId_IngresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Actividad
        {
            get
            {
                return _Id_Actividad;
            }
            set
            {
                OnId_ActividadChanging(value);
                ReportPropertyChanging("Id_Actividad");
                _Id_Actividad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Actividad");
                OnId_ActividadChanged();
            }
        }
        private global::System.Int32 _Id_Actividad;
        partial void OnId_ActividadChanging(global::System.Int32 value);
        partial void OnId_ActividadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mes
        {
            get
            {
                return _Mes;
            }
            set
            {
                OnMesChanging(value);
                ReportPropertyChanging("Mes");
                _Mes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mes");
                OnMesChanged();
            }
        }
        private global::System.String _Mes;
        partial void OnMesChanging(global::System.String value);
        partial void OnMesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha_ingreso
        {
            get
            {
                return _Fecha_ingreso;
            }
            set
            {
                OnFecha_ingresoChanging(value);
                ReportPropertyChanging("Fecha_ingreso");
                _Fecha_ingreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_ingreso");
                OnFecha_ingresoChanged();
            }
        }
        private global::System.DateTime _Fecha_ingreso;
        partial void OnFecha_ingresoChanging(global::System.DateTime value);
        partial void OnFecha_ingresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private Nullable<global::System.Int32> _DNI;
        partial void OnDNIChanging(Nullable<global::System.Int32> value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Pago
        {
            get
            {
                return _Id_Pago;
            }
            set
            {
                OnId_PagoChanging(value);
                ReportPropertyChanging("Id_Pago");
                _Id_Pago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Pago");
                OnId_PagoChanged();
            }
        }
        private global::System.Int32 _Id_Pago;
        partial void OnId_PagoChanging(global::System.Int32 value);
        partial void OnId_PagoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observaciones
        {
            get
            {
                return _Observaciones;
            }
            set
            {
                OnObservacionesChanging(value);
                ReportPropertyChanging("Observaciones");
                _Observaciones = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observaciones");
                OnObservacionesChanged();
            }
        }
        private global::System.String _Observaciones;
        partial void OnObservacionesChanging(global::System.String value);
        partial void OnObservacionesChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_Actividad", "Actividad")]
        public Actividad Actividad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Ingreso_Actividad", "Actividad").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Ingreso_Actividad", "Actividad").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actividad> ActividadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actividad>("AkrosModel.FK_Ingreso_Actividad", "Actividad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actividad>("AkrosModel.FK_Ingreso_Actividad", "Actividad", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_Alumno", "Alumno")]
        public Alumno Alumno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("AkrosModel.FK_Ingreso_Alumno", "Alumno").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("AkrosModel.FK_Ingreso_Alumno", "Alumno").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Alumno> AlumnoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alumno>("AkrosModel.FK_Ingreso_Alumno", "Alumno");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Alumno>("AkrosModel.FK_Ingreso_Alumno", "Alumno", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AkrosModel", "FK_Ingreso_FormaPago", "FormaPago")]
        public FormaPago FormaPago
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormaPago>("AkrosModel.FK_Ingreso_FormaPago", "FormaPago").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormaPago>("AkrosModel.FK_Ingreso_FormaPago", "FormaPago").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FormaPago> FormaPagoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FormaPago>("AkrosModel.FK_Ingreso_FormaPago", "FormaPago");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FormaPago>("AkrosModel.FK_Ingreso_FormaPago", "FormaPago", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
